config/routes.rb
Rails.application.routes.draw do

  resources :wikis do
    post '/collab_add' => 'wikis#collab_add', as: :collab_add
    post '/collab_remove' => 'wikis#collab_remove', as: :collab_remove
  end

  resources :charges, only: [:new, :create]

  devise_for :users

  get 'about' => 'welcome#about'

  resources :downgrade, only: [:index, :create]

  root 'welcome#index'

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base

  after_initialize :init

  has_many :wikis
  has_many :collaborators
  has_many :collab_wikis, through: :collaborators, source: :wiki

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,
         :authentication_keys => [:login]

   def login=(login)
     @login = login
   end

   def login
     @login || self.username || self.email
   end

   def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def init
    self.role ||= 0
  end


  validate :validate_username

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  enum role: [:standard, :premium, :admin]

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :collab_users, through: :collaborators, source: :user
  # scope :visible_to, -> (user) { user.premium? || user.admin? ? all : where(private: false) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include Pundit
  protect_from_forgery

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized


  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action!"
    redirect_to(root_path)
  end


end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  class Amount
    def self.default
      15_00
    end
  end

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Blocipedia Upgrade to Premimum - #{current_user.username}",
      amount: Amount.default
    }
  end

  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      amount: Amount.default,
      description: "Blocipedia Upgrade to Premimum - #{current_user.username}",
      :currency    => 'usd'
    )

    current_user.role = 1
    if current_user.save
      flash[:notice] = "Thank you, #{current_user.username}! You have successfully upgraded your account to PREMIUM.  You can now write Private Wikis!"
    else
      flash[:alert] = "There was a problem updating you account!  Please contact the system admin."
    end

    # redirect_to user_path(current_user.username)
    redirect_to root_path

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end

end

app/controllers/downgrade_controller.rb
class DowngradeController < ApplicationController


  def create
    # flash[:notice] = "USER WAS: #{current_user}"
    current_user.role = 0
    @wikis = Wiki.all
    @wikis.each do |wiki|
      if wiki.private == true && wiki.user_id == current_user.id
        wiki.private = false
        wiki.save!
      end
    end
    if current_user.save
      flash[:notice] = "Thank you, #{current_user.username}! You have successfully downgraded your account to STANDARD."
    else
      flash[:alert] = "There was a problem updating you account!  Please contact the system admin."
    end
    redirect_to root_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new
    @wiki.assign_attributes(wiki_params)
    @wiki.user_id = current_user.id

    if @wiki.save
      flash[:notice] = "Wiki was saved successfully."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @collab_users = @wiki.collab_users.all

    users_all = User.all
    users_available = []
    users_all.each do |user|
      if current_user.id != user.id && !@collab_users.include?(user)
        users_available << user
      end
    end
    @collaborators = users_available

  end


  def collab_add
    @wiki = Wiki.find(params[:wiki_id])
    user = User.find(params[:user_id])

    @wiki.collaborators.create(user: user)
    flash[:notice] = "Collaborator Added"
    redirect_to edit_wiki_path(@wiki)
  end


  def collab_remove
    @wiki = Wiki.find(params[:wiki_id])
    user = User.find(params[:user_id])
    collaborator = @wiki.collaborators.where(user_id: user)

    if @wiki.collaborators.destroy(id = collaborator)
      flash[:notice] = "Collaborator Removed"
    else
      flash.now[:alert] = "There was an error removing that collaborator. Please try again."
    end
    redirect_to edit_wiki_path(@wiki)
  end


  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)

    authorize @wiki
    if @wiki.save
      flash[:notice] = "Wiki was updated successfully."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end

  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
    renderer = Redcarpet::Render::HTML.new()
    Redcarpet::Markdown.new(renderer, extensions = {}).render(text).html_safe
  end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/downgrade_helper.rb
module DowngradeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if user_signed_in? %>
    Signed in as: <strong><%= current_user.username %></strong>, Level: <strong><%= current_user.role %></strong> |
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
    <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>

  <div class="container">
    <ul class="nav nav-tabs">
     <li><%= link_to "Home", root_path %></li>
     <li><%= link_to "About", about_path %></li>
     <li><%= link_to "Wikis", wikis_path %></li>
  </div>

  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash.now[:alert] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash.now[:alert] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>


<%= yield %>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/about.html.erb
<h1>About Blocipedia</h1>
<p>Nothing here yet.</p>

app/views/welcome/index.html.erb
<h1>Welcome to Blocipedia</h1>

<p id="index-title">- Blocipedia -</p>


 <div class="posts">Post 1 placeholder</div>

 <section>Section placeholder</section>

app/views/wikis/_form.html.erb
<%= form_for wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>

  <% if current_user.admin? || current_user.premium? %>
    <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>Make it awesome.</li>
      <li>NOTE: <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown</a> syntax supported!</li>
    </ul>
    <% if (current_user.premium? && @wiki.user_id == current_user.id) || current_user.admin? %>

      <p><strong>Wiki Collaborators:</strong></p>
      <ul>
        <% @collab_users.each do |collab_user| %>
          <li><%= collab_user.username %></li>
        <% end %>
      </ul>
      <%= form_tag(wiki_collab_remove_path(@wiki), remote: true, id: "RemoveCollab") do %>
        <input id="r_textbox" type="text" /><br />
        <%= select_tag :user_id, options_for_select(@collab_users.collect { |c| [ c.username, c.id ] }), id: 'remove_textbox' %>
        <%= submit_tag "Remove", method: :collab_remove, class: 'btn btn-success', data: {confirm: 'Are you sure you want to remove this collaborator?'} %>
      <% end %>

      <p><strong>Add New Collaborator:</strong></p>
      <%= form_tag(wiki_collab_add_path(@wiki), remote: true, id: "AddCollab") do %>
        <input id="a_textbox" type="text" /><br />
        <%= select_tag :user_id, options_for_select(@collaborators.collect { |c| [ c.username, c.id ] }), id: 'add_textbox' %>
        <%= submit_tag "Add", method: :collab_add, class: 'btn btn-success', data: {confirm: 'Are you sure you want to add this user?'} %>
      <% end %>

    <% end %>

  </div>
  <div class="col-md-8">

    <%= render partial: 'form', locals: { wiki: @wiki } %>

  </div>
</div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>

<% @wikis.each do |wiki| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to wiki.title, wiki %>
        <% if wiki.private %>
          <span class="bg-warning">Private</span>
        <% end %>
      </h4>
    </div>
  </div>
<% end %>

<div class="col-md-4">
  <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>Make it awesome.</li>
      <li>NOTE: <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown</a> syntax supported!</li>
    </ul>
  </div>
  <div class="col-md-8">

    <%= render partial: 'form', locals: { wiki: @wiki } %>

  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body) %></p>
  </div>

  <% if user_signed_in? %>
    <div class="col-md-4">
      <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
      <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
    </div>
  <% end %>

</div>